### ISSUE TITLE
v1.1.6: goimports not working after update

### ISSUE THREAD

**Issue by britannic** [joefitzgerald/gofmt#17]
Updated gofmt to v1.1.6 and goimports is now broken in the editor (cmd line tool works fine)

I made sure I have the latest goimports:

go get -u golang.org/x/tools/cmd/goimports

No competing goimports is installed.

atom --version
1.6.2

Mac OS X El Capitan: 10.11.4 (15E65)

Format on Save is checked
Format Tool selected is "go imports"

This is the error that is showing up in the Atom Developer Console:

gofmt: (stderr) flag provided but not defined: -srcdir
usage: goimports [flags] [path ...]
  -d    display diffs instead of rewriting files
  -e    report all errors (not just the first 10 on different lines)
  -l    list files whose formatting differs from goimport's
  -w    write result to (source) file instead of stdout

**Comment by fyelles** [comment]
+1

**Comment by fyelles** [comment]
@joefitzgerald Any insight ?

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/gofmt/issues/15#issuecomment-206538329 the only explanation for this is you are running an old version of goimports. Please make sure you run `which -a goimports` and delete all of them. Additionally delete them from all $GOPATH/bin locations (especially if you have multiple GOPATHs or GOPATH entries). Then run the go get command again.

**Comment by britannic** [comment]
@joefitzgerald, the "-a" switch was a great tip, I found the older version lurking in my personal $GOBIN, removed it and now all is fully functional - thanks for the quick update and also for all of your hard work in providing a highly valued addition to the Atom Editor for our Golang experience!!!!!

**Comment by nilstgmd** [comment]
Additional info, sometimes removing the result of `which -a goimports` will not work alone. 

In those cases `go get -u golang.org/x/tools/cmd/goimports` will returning `abort: HTTP Error 404: Not Found` because the mercurial path it tries to pull from doesn't exist anymore. You also have to `rm -rf $GOPATH/src/golang.org/x/tools` in that case, to make go fetch it from its new location. After that I was able to make `gofmt` working again with `goimports`.

HTH
