### ISSUE TITLE
CPU spikes on save with gofmt enabled

### ISSUE THREAD

**Issue by ianwalter** [joefitzgerald/gofmt#27]
`goimports` shoots to the top of the process list and Atom freezes up for a few seconds. It seems to only happen on my "command" files where I import `"github.com/spf13/cobra"`. I've done some work on that project in the past but I'm not sure what's happening here. Any help would be greatly appreciated! Thank you.

**Comment by ianwalter** [comment]
Going to close this as it's probably an issue with goimports. Atom occasionally doesn't show me package settings so I didn't know you could select the tool on save. That option might be better as a series of checkboxes than a dropdown though.

**Comment by joefitzgerald** [comment]
It's a drop down because gofmt, goimports, and goreturns are mutually exclusive. There are commands in the command pallete to run any of hem individually against the current buffer.

I've seen one other user with this behavior too. It would be good to try and triangulate any commonalities between you both. Will connect the dots tomorrow.
